### PR TITLE
Support passing lists to Decimal.max and Decimal.min

### PR DESCRIPTION
**Pull request by andruby**
Sometimes you need to find the lowest or highest value of a list of Decimals. This PR provides that.

Let me know what I can do to improve the code or documentation.

### CODE REVIEW

**Comment by ericmj** [comment]
I don't think this functionality is needed since you can achieve the same thing with reduce: `Enum.reduce(tail, head, &Decimal.max/2)` and it's not much more code.

**Comment by andruby** [comment]
I hadn't thought about using reduce that way. That does make it concise. 

I do think that `Decimal.max(list)` is a little clearer and faster to read. But I understand if you want to keep the library small.

**Comment by ericmj** [comment]
> I do think that Decimal.max(list) is a little clearer and faster to read. But I understand if you want to keep the library small.

I agree that it is clearer and faster to read but do I want to keep the library minimal :)

**Comment by andruby** [comment]
It does make it easier to use in pipes ¯\_(ツ)_/¯

```elixir
max_price = list_of_structs
|> Enum.map(&(&1.price))
|> Decimal.max
```

vs 

```elixir
prices = list_of_structs
|> Enum.map(&(&1.price))
[head_price|tail_prices] = prices
max_price = Enum.reduce(tail_prices, head_price, &Decimal.max/2)
```

**Comment by ericmj** [comment]
```elixir
max_price = list_of_structs
|> Enum.map(&(&1.price))
|> Enum.reduce(&Decimal.max/2)

**Pull request closed without merging**
