### PR TITLE
Fix Elixir 1.4 warnings

### PR DESCRIPTION
**Pull request by whatyouhide**

### CODE REVIEW

**Comment by ericmj** [comment]
:heart:

**Comment by CharlesOkwuagwu** [comment]
I thought you could leave off () if a function has arity 0

Has this changed in 1.4?

**Comment by whatyouhide** [comment]
@CharlesOkwuagwu yes, we are now emitting a warning if the function has arity 0 *and* is a local function or imported function; this is because these functions, if called without parens, can be easily mistaken for variables, making code more confusing to read and understand.

**Comment by CharlesOkwuagwu** [comment]
@whatyouhide Some of us follow the Elixir Style Guide ... maybe you could point it out to folks there, and also in your standard getting started docs

**Comment by ericmj** [comment]
@CharlesOkwuagwu The guides are for stable elixir. We will update the necessary places when 1.4 ships.

**Pull request merged**
