### PR TITLE
Include the given value as part of the `error-reason`

### PR DESCRIPTION
**Pull request by CharlesOkwuagwu**

### CODE REVIEW

**Comment by CharlesOkwuagwu** [comment]
How do you mean? Isn't bin the original string that the user intended to format as a decimal?

**Comment by ericmj** [comment]
It will be downcased and removed the sign.

**Comment by CharlesOkwuagwu** [comment]
Ah, I see. Well, it would really help if we could see the original data that was being formatted

**Comment by CharlesOkwuagwu** [comment]
It's good to show what piece of data caused the error.

**Comment by CharlesOkwuagwu** [comment]
> It will be downcased and removed the sign.

That's fine, at least we get some indication of the `value` that caused the error.

**Comment by ericmj** [comment]
Can you instead include the full string in the error message?

**Comment by CharlesOkwuagwu** [comment]
There was a mismatch in the data source columns, by adding the `<> bin`, it was easily clear where the source of the error was:

```
iex(4)> ERR: DFR114 
%Decimal.Error{message: ": number parsing syntax: 22-apr-2016", reason: "number parsing syntax: 22-apr-2016", result: #Decimal<sNaN>, signal: nil}
    (decimal) lib/decimal.ex:904: Decimal.new/1
    (rmas) lib/rmas/report.ex:545: RMAS.Report.format_val/2
    (rmas) lib/rmas/report.ex:488: anonymous fn/2 in RMAS.Report.xml_data/5
    (elixir) lib/enum.ex:1060: anonymous fn/4 in Enum.group_by/3
    (elixir) lib/enum.ex:1811: Enum."-group_by/3-lists^foldl/2-0-"/3
    (rmas) lib/rmas/report.ex:488: RMAS.Report.xml_data/5
    (rmas) lib/rmas/report.ex:473: anonymous fn/5 in RMAS.Report.xml_body/5
    (stdlib) lists.erl:1263: :lists.foldl/3

```

**Comment by ericmj** [comment]
Sorry, I mean can you change your PR to include the full string passed to `Decimal.new`.

**Comment by CharlesOkwuagwu** [comment]
> Sorry, I mean can you change your PR to include the full string passed to Decimal.new.

Done.

**Comment by ericmj** [comment]
Thank you!

**Pull request merged**
