### PR TITLE
Macro check

### PR DESCRIPTION
**Pull request by razuf**
Thanks for the macro idea @wojtekmach !

I hope that's what you mean.

Not all edge cases are fixed, but the most important ones for the inbound (see tests).

The normal way for current Elixir Version would be:

```elixir
def new(%Decimal{} = num) when is_decimal(num), do: num
```

But thats not working with Elixir 1.2.6 - thats why:

```elixir
  def new(%Decimal{} = num) do
    if is_decimal(num),
      do: num,
      else: raise(Error, reason: "wrong decimal number: #{inspect(num)}")
  end
```
Any other idea for 1.2.6? ;-)
 
I really appreciate your help with all of this!

btw. this PR would fix the Money problem:

```elixir
iex(1)> m = Money.new(:USD, Decimal.new(%Decimal{sign: -1, coef: -12000000000}))
** (Decimal.Error) : wrong decimal number: #Decimal<--12000000000>
    (decimal 1.8.1) lib/decimal.ex:1101: Decimal.new/1
```

### CODE REVIEW

**Comment by razuf** [comment]
@wojtekmach :
> I believe extending the is_decimal/1 macro further would have small additional runtime cost too but perhaps it's negligible anyway.

Yes the differences are not measurable (benchee):

```elixir
inputs = %{
  "a 1 Digits Input as String" => {"6", "9"},
  "b 3 Digits Input as String" => {"123", "654"},
...
}
```

```elixir
  "Decimal.div()    Int" => fn {l, r} ->
    Decimal.div(l, r) |> Decimal.to_string()
  end
```

orig version "2.0.0-rc.0":

```elixir

##### With input a 1 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      144.00 K        6.94 μs    ±75.74%        6.99 μs       12.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         3.61 KB

**All measurements for memory usage were the same**

##### With input b 3 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      155.00 K        6.45 μs   ±353.05%        5.99 μs        9.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         3.03 KB

**All measurements for memory usage were the same**

##### With input c 6 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      140.39 K        7.12 μs    ±57.73%        6.99 μs       11.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         4.22 KB

**All measurements for memory usage were the same**

##### With input d 15 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      144.01 K        6.94 μs    ±54.90%        6.99 μs       16.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         4.28 KB

**All measurements for memory usage were the same**

##### With input e 30 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       70.38 K       14.21 μs    ±33.47%       13.99 μs       34.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         5.78 KB

**All measurements for memory usage were the same**

##### With input f 120 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       54.38 K       18.39 μs    ±19.09%       17.99 μs       24.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        13.56 KB

**All measurements for memory usage were the same**

##### With input g 240 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       38.45 K       26.01 μs    ±21.26%       24.99 μs       53.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        20.03 KB

**All measurements for memory usage were the same**

##### With input h 606 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       19.48 K       51.34 μs    ±18.06%       48.99 μs       90.99 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        44.86 KB

**All measurements for memory usage were the same**

```

new version with Macro check branch:

```elixir
##### With input a 1 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      148.16 K        6.75 μs    ±31.42%           7 μs          10 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         3.61 KB

**All measurements for memory usage were the same**

##### With input b 3 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      156.26 K        6.40 μs    ±83.06%           6 μs          12 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         3.03 KB

**All measurements for memory usage were the same**

##### With input c 6 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      146.37 K        6.83 μs    ±43.67%           7 μs          11 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         4.22 KB

**All measurements for memory usage were the same**

##### With input d 15 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int      146.17 K        6.84 μs    ±58.69%           7 μs          12 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         4.28 KB

**All measurements for memory usage were the same**

##### With input e 30 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       71.02 K       14.08 μs    ±52.79%          13 μs          29 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int         5.78 KB

**All measurements for memory usage were the same**

##### With input f 120 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       53.68 K       18.63 μs    ±27.47%          18 μs          23 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        13.56 KB

**All measurements for memory usage were the same**

##### With input g 240 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       39.73 K       25.17 μs    ±15.24%          24 μs          43 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        20.03 KB

**All measurements for memory usage were the same**

##### With input h 606 Digits Input as String #####
Name                           ips        average  deviation         median         99th %
Decimal.div()    Int       19.65 K       50.90 μs    ±14.90%          49 μs          84 μs

Memory usage statistics:

Name                    Memory usage
Decimal.div()    Int        44.86 KB

**All measurements for memory usage were the same**
```

**Comment by ericmj** [comment]
Using `is_decimal/1` for this is not correct unfortunately. The guard checks if it's a decimal, not a valid decimal. We don't want an invalid decimal to return `false`, it should raise an error. We can't raise errors in guards so this is not option unfortunately.

This change helps in your money example because you pass the manually crafted struct to `Decimal.new/1` but that's unnecessary since it's a noop. So it would only help if the user is doing unnecessary function calls.

**Comment by wojtekmach** [comment]
@razuf yeah that is exactly what I had in mind, thank you for trying this out. As I mentioned in the previous comment, (and sorry if I send mixed messages), I still think we shouldn't do it and instead assume the structs were constructed properly. I don't expect that we'd have for example extra checks in `Date` to protect against `%Date{year: :Y2K}`. I guess that's something we have to live with in a dynamically typed language. (Maybe it's bad example as `%Date{year: :Y2K}` will fail early but the Decimal examples you gave are more subtly and more dangerously incorrect, they don't raise but give wrong result.)

**Comment by razuf** [comment]
Thanks a lot about investigate this PR and that you took again the time to check my suggestion.
I can really follow your arguments of having a dynamically typed language and guard argument of no error and so on! 

What if this PR would only change the new/1 to check the input in the same way like new/3:
```elixir
  def new(%Decimal{sign: sign, coef: coef, exp: exp} = num)
      when sign in [1, -1] and ((is_integer(coef) and coef >= 0) or coef in [:NaN, :inf]) and
             is_integer(exp),
      do: num
```

instead of:

```elixir
  def new(%Decimal{} = num), do: num
```

the current new/3 is looks like:

```elixir
  def new(sign, coef, exp)
      when sign in [1, -1] and ((is_integer(coef) and coef >= 0) or coef in [:NaN, :inf]) and
             is_integer(exp),
      do: %Decimal{sign: sign, coef: coef, exp: exp}
```

What do you think?

**Comment by ericmj** [comment]
Yeah, it makes sense that `new/1` validates all input it gets. Sounds like a good change. 👍

**Comment by razuf** [comment]
thanks! that helps a lot in my case! ;-)

**Comment by razuf** [comment]
;-) all checks are fine down to v1.2

**Comment by razuf** [comment]
and tests of course for that - I'm quite happy that the sqrt infinite loop is gone now. :-D

**Comment by wojtekmach** [comment]
Thank you!

**Comment by ralphshelfshot** [comment]
Thanks @wojtekmach  ... sorry I was 12 seconds to late ;-)

**Comment by ralphshelfshot** [comment]
yes sorry ;-)

 if you have a litle time please read it. thanks

**Pull request merged**
