### PR TITLE
Use the context rounding algorithm as the default

### PR DESCRIPTION
**Pull request by aptinio**

### CODE REVIEW

**Comment by ericmj** [comment]
The context rounding is used when values are produced that doesn't fit into the context's configured precision. This is separate from the explicit rounding with `Decimal.round` so I don't we should use reuse the context's rounding for it.

**Comment by aptinio** [comment]
Thanks for looking into this. Here's a test for the behavior I find surprising. I should've included it in the first place.

```elixir
  test "round/2" do
    assert Decimal.round(~d"1.025", 2) == d(1, 103, -2)

    Context.with(%Context{rounding: :half_down}, fn ->
      assert Decimal.round(~d"1.025", 2) == d(1, 102, -2)
    end)
  end
```

I understand that this is a breaking change and I'd respect your decision if it stays the same.

**Comment by ericmj** [comment]
Thanks for the clarification. My thinking is still the same for this. The rounding mode specified in the context is only used when you have implicit rounding from an operation that hit the precision limit specified in the context. The explicit rounding with `Decimal.round` should not be affected by anything specified in the context.

**Comment by aptinio** [comment]
Okay, that makes sense. Thank you! <3

**Pull request closed without merging**
